### ISSUE TITLE
Demo Dynamic: fint field & null 

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#1]
In new Dynamic Controller, when saving without a fint value:

> Cannot insert the value NULL into column 'fint', table 'demo.dbo.demos'; column does not allow nulls. INSERT fails.
> The statement has been terminated.

**Comment by osalabs** [comment]
fixed by converting all "number" field to number.
If we will need NULLable int/float fields in the future, possible solutions:
- just make field type "input"
- or implement additional "is_nullable" option per field
