### ISSUE TITLE
Dynamic Controller: Disallow sorting for selected fields in list view

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#17]
It would be nice to have the ability to disallow sort action for selected columns in dynamic controller list view.
Probably by putting empty value in `"list_sortmap"` fields list in `config.json`, for example if I don't want user to sort by `iname`:
```
"list_sortmap": "id|id iname| icode|icode",
```

**Comment by osalabs** [comment]
Done in this way:
- if `config.json` contains `"list_sortmap"` - it will override dynamic controller's default behaviour of adding all fields to sortmap
- if `"list_sortmap"` contains empty value after "|" - this field won't be sortable too. Basically don't need to include field in sortmap at all if you don't want to sort by it
