### ISSUE TITLE
Nullable number become 0 in Dynamic Controller

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#22]
If I have a "number" field in config.json and it's also in "save_fields_nullable" the resulting DB saved value is 0, not NULL. It's becase of `processSaveShowFormFields:528`:
```
fields(field) = Utils.f2float(fields(field))
```
There is a suggestion to remove "save_fields_nullable" from config.json and simply add new Boolean "nullable" attribute to fields configuration.

**Comment by osalabs** [comment]
For now we will leave save_fields_nullable as it's used in non-dynamic controllers
