### ISSUE TITLE
logs, main.log file location

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#23]
1. Placing main.log under App_Data requires to grant write permission for the whole App_Data. Or creating an empty "main.log", grant permission to it and periodically truncating. I recommend putting log files outside the "www" dir, or at least under separate "logs" dir in "www".

2. It seems that some projects have "main.log" without any rotation. It'll be good to truncate it automatically if some size reached (100MB).

**Comment by osalabs** [comment]
Done. main.log moved to /App_Data/logs/main.log
And also added simple rotation - if log file grows more than 100MB (currently hardcoded in FwConfig) it's moved to main.log.1
