### ISSUE TITLE
add .on-refresh class change event in fw.js

### ISSUE THREAD

**Issue by KrNikita** [osalabs/osafw-asp.net#28]
in fw.js add 
$(document).on('change', '.on-refresh', function (e) {
    var $f = $(this).closest('form');
    $f.find('input[name=is_refresh]').val(1);
    $f.submit();
});

to by default have event which refresh form if input with on-refresh class changed

**Comment by osalabs** [comment]
Done, implemented standard support for the form reload:
- apply .on-refresh class to the input/select control
- when the control chages - form submitted with "refresh=1" parameter
- `SaveAction()` detect this parameter and return back to `ShowFormAction` instead processing db update
