### ISSUE TITLE
Yes/No for Admin::Show

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#29]
In DemosDynamic config.json there is the following item for Yes/No field:
```
        {
            "field": "fyesno",
            "label": "Yes or No",
            "type": "plaintext",
            "lookup_tpl": "/common/sel/yn.sel"
        },
```

However, it doesn't work if the field is a BIT type, not the TINYINT, because BIT type returns True/False.

I had to create "/common/sel/yn_tf.sel" with this content to make it work.
```
False|`No`
True|`Yes`
```

What is the correct approach? As ParsePage evaluates True/False strings correctly for if/unless statements, should we include this "yn_tf.sel" into the framework and use this template during controllers generation if the column type in DB is BIT?

**Comment by osalabs** [comment]
The following changes made:
- changed `demos.fyesno` to BIT type for demo purposes
- created `/common/sel/yn_bool.sel`
- updated config.json for DemosDynamic accordingly
