### ISSUE TITLE
Restore from trash link button

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#32]
It'd be good to display a "Restore" link button instead of a "Del" when "Trashed" filter is selected:

![image](https://user-images.githubusercontent.com/35847544/83323947-9a77d880-a26a-11ea-8926-958233474922.png)

Or, probably: "View - Edit - Restore - Del Forever"

"Del Forever" should be displayed only if some global setting in web.config is set, like "LIST_ITEMS_FORCE_DELETE_DEFAULT = True"

**Comment by osalabs** [comment]
I decided to leave only View/Edit on the list screen.
Del button available as commented subtemplate.

Delete, Restore and Permanent Delete now available on View screen.
