### ISSUE TITLE
"save_fields_nullable" and dynamic controller generation

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#34]
After dynamic controller generation I have to dump the correspondent DB table scheme, extract all NULL-able fields and add them to "save_fields_nullable" in config.json.

Preserving NULL-able behavior is important in Access migration projects where ```IS [NOT] NULL``` is widely used and when the web fronted and the old Access application is used simultaneously. So, it'll be nice to analyze database fields and populate "save_fields_nullable" automatically.

**Comment by osalabs** [comment]
It should work correctly in latest version
