### ISSUE TITLE
Dynamic controllers generation and DB VIEWS

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#35]
When I create a dynamic controller that based on the view and that view contains aliases for the source table, I want only those aliases to be used in config.json, and skip the source table names.

For example, if I have a table ```tblProperties```, and then I create a VIEW based on this table to conform to the OSAFW naming convention:

```CREATE VIEW properties AS
SELECT
 PropertyID as id
 , ClientID as clients_id
 , Property as iname
 , Notes as idesc
 , pr.*
FROM tblProperties pr
```

I want the original "PropertyID ", "ClientID ", "Property ", and "Notes" name fields to be excluded from the config.json.

For now we have duplicates that have to be manually removed from the config.json which is a quite time consuming.

**Comment by osalabs** [comment]
Best practice would be to include only required fields into the view, not the `pr.*`

I.e. when working on a database with existing tables, first - create views that will contain all the fields with proper names. And only after - generate models/controllers.
