### ISSUE TITLE
FwController::getListRows list_view name starts with space

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#41]
This will not work if my `list_view = " (SELECT * FROM ...."`:
```
Dim list_view_name = IIf(list_view.Substring(0, 1) = "(",
```
always Trim list)view value?

I personally didn't experienced this, but it seems developers may stumble upon it ...

**Comment by osalabs** [comment]
Nothing to fix, just always start list_view with "(" if it's a subquery.
