### ISSUE TITLE
Dynamic controller: custom model call with parameters

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#8]
I'd like to have the implementation in dynamic controller to make this work out of the box:

        `{
            "field": "some_primary_id",
            "label": "My Label",
            "custom_lookup_model": "MyCustomModel",
            "custom_lookup_model_func": "myCustomFunction",
            "custom_lookup_model_args": "category=somestring, type1=somestring2",
            "type": "select"
        }`

Or more concisely:

        `{
            "field": "some_primary_id",
            "label": "My Label",
            "custom_lookup_model": "MyCustomModel.myCustomFunction('category=somestring, type1=somestring2')",
            "type": "select"
        }`

and to have a call in the code
`def("select_options") =  fw.model("MyCustomModel").myCustomFunction("category=somestring, type=somestring2", def("field"), item(def("field"), def("type") )`

And, probably, I will need the same for a "custom_lookup_field", as well as for "multi_datarow"-like type:

       `{
            "field": "some_primary_id",
            "label": "My Label",
            "type": "plaintext",
            "custom_lookup_model": "MyCustomModel.myCustomFunction('category=somestring, type1=somestring2')",
            "custom_lookup_field": "my_field_name",
        }`

`def("value") =  fw.model("MyCustomModel").myCustomFunction("category=somestring, type=somestring2", def("field"), item(def("field"), def("type"), def("custom_lookup_field"))`

`def("row") = ... ' introduce new type ="datarow"`

`def("rows") = ... ' introduce new type ="datarows"`

Of course, it may be better to pass a hash to this custom function in order to have arbitrary order and arguments number.

I want this because I have some tables like this:

> id, category, type, description
> 1, cat1, type1, text1
> 2, cat1, type2, text2
> 3, cat1, type2, text3
> 4, cat2, type4, text4
> 5, cat2, type4, text5
> 6, cat3, type5, text6

and so on, and so on. And I need to make up different select options by several fields, i.e `listSelectOptionsByCat1Type2()`, `listSelectOptionsByCat2Type4()` etc. 

I want to have just one model file, and one `listSelectOptionsCustom(args As String, ...)` or `listSelectOptionsCustom(params As Hashtable)` , and then parse those `args` or `params("args")` to adjust the SQL-query accordingly. 

And I also need the parameters of filed name, value and type to be passed as well (`def("field"), item(def("field"), def("type"), def("custom_lookup_field")`) to have more flexibility.

**Comment by osalabs** [comment]
in order to keep config.json simple and declarative I only added optional `lookup_params` for `lookup_model`, so now it's possible to do this:
```
        {
            "field": "dict_link_multi",
            "label": "DemoDicts Multi",
            "type": "multicb",
            "lookup_model": "DemoDicts",
            "lookup_params": "some optional params"
        },
```
and then you could override `getMultiList` or `listSelectOptions` (which now has `Optional params as Object = Nothing`) in your specific model and use params as necessary.
