### ISSUE TITLE
"data-" html attirbutes for Dynamic controller

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net#9]
It'd be nice to set data- attributes via .JSON config, i.e. to set selectpicker or don't autosave some field (data-noautosave).

**Comment by osalabs** [comment]
For showform fields in config.json added options:
`attrs` - for outer element (`<div>`)
`attrs_control` - for control element (`<input>` or `<~select>`)

added for most of types, but not all (for example not to multi control types). We'll add it later if it will be really required.
